### ISSUE TITLE
Long running test

### ISSUE THREAD

**Issue by echarles** [jupyter-rtc/jupyterlab#12]
@dmonad @@hbcarlos This is follow up of https://github.com/jupyter-rtc/jupyterlab/pull/11#issue-601877784

The tests are still running. But they now take much longer because yjs_echo_server is working in the background and is never killed. @echarles or @hbcarlos Could you look into that?

**Comment by hbcarlos** [comment]
I'm looking into this.

**Comment by jtpio** [comment]
By the way, should the tests be enabled to run on this fork? (it doesn't seem to be the case when looking at the PRs)

It could be that GitHub Actions were not enabled here since this is a fork project.

**Comment by dmonad** [comment]
I was wondering about that. I'm gonna check if it is possible to enable them.

**Comment by echarles** [comment]
In general, it is not clear to me if github actions are run on a fork. I had the feeling that actions were run on push on my forks.

This is what we have for this repo (@dmonad you are also admin, so you can try something...)

<img width="837" alt="Screenshot 2021-03-29 at 16 50 52" src="https://user-images.githubusercontent.com/226720/112855441-158a6500-90af-11eb-85c1-75d850296ab1.png">

**Comment by dmonad** [comment]
You basically have to add payment options to the organization and then add a GitHub-hosted runner.

**Comment by dmonad** [comment]
Without payment options, you only have access to self-hosted runners (that you would have to setup manually)

**Comment by jtpio** [comment]
Right, probably because `jupyter-rtc` is an organization (enabling GitHub Actions for forks on personal accounts seems to be fine though).

**Comment by dmonad** [comment]
So it was not the payment options. I only had to enable the actions manually in the actions menu (they were disabled by default because this is a fork).
