### ISSUE TITLE
Better docprovider interface

### ISSUE THREAD

**Issue by echarles** [jupyter-rtc/jupyterlab#13]
@dmonad @@hbcarlos This is follow up of https://github.com/jupyter-rtc/jupyterlab/pull/11#issue-601877784

The docprovider needs a better interface that also handles context information - i.e. the modified timestamp. This API probably also can handle file-type information (currently defined in codeeditor). @echarles Could you work on that?

**Comment by dmonad** [comment]
I'm closing this because it is pretty unspecific.
