### ISSUE TITLE
Text file content not-synced when opened for the second time

### ISSUE THREAD

**Issue by echarles** [jupyter-rtc/jupyterlab#14]
@dmonad @@hbcarlos This is follow up of https://github.com/jupyter-rtc/jupyterlab/pull/11#issue-601877784

The content of a text-files is neither synced nor initialized with content from the filesystem (when it is opened a second time).

**Comment by echarles** [comment]
@hbcarlos Would be great if you can give more background on https://github.com/jupyter-rtc/jupyterlab/pull/48#issuecomment-817895750 and discuss ways to further fix.

**Comment by hbcarlos** [comment]
Actually, this issue is fixed and we can close it. The new one is #49 

Now text editors are in sync, we can open a text file, markdown, ... and they are collaborative. The only missing part is opening a Notebook with the notebook editor and text editor at the same time.

**Comment by hbcarlos** [comment]
Fixed in #48
