### ISSUE TITLE
An empty cell is added every time a browser opens a document

### ISSUE THREAD

**Issue by echarles** [jupyter-rtc/jupyterlab#15]
@dmonad @@hbcarlos This is follow up of https://github.com/jupyter-rtc/jupyterlab/pull/11#issue-601877784

An empty cell is added every time a browser opens a document. The fix for this issue can be ported from our first RTC attempt - Kevin / Eric / Carlos

**Comment by dmonad** [comment]
I disabled this feature because it broke a test. Probably nothing critical. Ideally, we find a way to fix this without updating the tests, so we retain the same interface.

**Comment by dmonad** [comment]
Fixed in #42
