### ISSUE TITLE
Shared UndoManager needs to be implemented

### ISSUE THREAD

**Issue by echarles** [jupyter-rtc/jupyterlab#18]
@dmonad @@hbcarlos This is follow up of https://github.com/jupyter-rtc/jupyterlab/pull/11#issue-601877784

Shared UndoManager needs to be implemented. - Kevin

**Comment by echarles** [comment]
This should be fixed with https://github.com/jupyter-rtc/jupyterlab/pull/32 Correct?

**Comment by dmonad** [comment]
Yep
