### ISSUE TITLE
Service tests failling

### ISSUE THREAD

**Issue by hbcarlos** [jupyter-rtc/jupyterlab#23]
## Description
This is a continuation of #12.
Sometimes there is an error with jest because JupyterLab doesn't shut down properly while running the test and makes jest hit a timeout and fail.

Was a [PR]( https://github.com/jupyterlab/jupyterlab/pull/9806) in lab to solve this. I'm not sure why still happening.

## Reproduce
Running the test locally.

## Context
<details><summary>Test Output</summary>
<pre>
@jupyterlab/services: Summary of all failing tests
@jupyterlab/services: FAIL test/kernel/ikernel.spec.ts (394.078 s)
@jupyterlab/services:   ● Kernel.IKernel › #restart() › should dispose of existing comm and future objects
@jupyterlab/services:     : Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.Error:
@jupyterlab/services:       35 | /* eslint-disable jest/no-export */
@jupyterlab/services:       36 | export function flakyIt(name: string, fn: any, retries = 3, wait = 1000): void {
@jupyterlab/services:     > 37 |   test(name, async () => {
@jupyterlab/services:          |   ^
@jupyterlab/services:       38 |     let latestError;
@jupyterlab/services:       39 |     for (let tries = 0; tries < retries; tries++) {
@jupyterlab/services:       40 |       try {
@jupyterlab/services:       at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
@jupyterlab/services:       at Object.flakyIt (../../testutils/src/flakyIt.ts:37:3)
@jupyterlab/services:       at Suite.<anonymous> (test/kernel/ikernel.spec.ts:663:5)
@jupyterlab/services:       at Suite.<anonymous> (test/kernel/ikernel.spec.ts:622:3)
@jupyterlab/services:       at Object.<anonymous> (test/kernel/ikernel.spec.ts:37:1)
@jupyterlab/services: Test Suites: 1 failed, 23 passed, 24 total
@jupyterlab/services: Tests:       1 failed, 452 passed, 453 total
@jupyterlab/services: Snapshots:   0 total
@jupyterlab/services: Time:        576.128 s
@jupyterlab/services: Ran all test suites.
@jupyterlab/services: Summary of failed tests
@jupyterlab/services: test/kernel/ikernel.spec.ts
@jupyterlab/services:   Kernel.IKernel
@jupyterlab/services:     #restart()
@jupyterlab/services:       ✕ should dispose of existing comm and future objects
</pre>
</details>

**Comment by hbcarlos** [comment]
I think this issue is related to https://github.com/jupyterlab/jupyterlab/pull/9997 since both test failings are related to `sessionContext`.

Probably rebasing from upstream will solve them.

cc @jtpio could have more info

**Comment by jtpio** [comment]
> Probably rebasing from upstream will solve them.

I think so yes. Looks like the fork is a little bit behind at the moment:

![image](https://user-images.githubusercontent.com/591645/113137705-2d83f500-9225-11eb-89f7-8afef730ec55.png)

**Comment by m2-farzan** [comment]
I'm having the same issue with the master branch of upstream.

The weird part is that GitHub CI is passing without errors. It turns out that the test command in CI script is slightly different from the one in the dev guide.

[CI script](https://github.com/jupyterlab/jupyterlab/blob/master/scripts/ci_script.sh) is doing something like this:
```
cd packages/services
jlpm run build:test
jlpm run test:cov
```
while [dev guide](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html) instructs to do this:
```
cd packages/services
jlpm run build:test
jlpm test
```

The former passes, the latter fails.

I have no idea what that `:cov` does, but IMHO maybe it needs to be reconsidered as it is (A) hiding errors (B) different from dev guide.

**Comment by jtpio** [comment]
Looks like upstream JupyterLab has this for the tests command at the moment:

https://github.com/jupyterlab/jupyterlab/blob/8e19d5b526e26c5f97066bd602e49ecfca67f3ba/packages/services/package.json#L42-L43

```json
"test": "jest",
"test:cov": "jest --collect-coverage",
```

While for this fork it is:

https://github.com/jupyter-rtc/jupyterlab/blob/22687170b01a50b36d8d311d2f20ca1fecb56191/packages/services/package.json#L42-L43

Which might explain the difference.

**Comment by jtpio** [comment]
BTW I pushed a rebase of ` jupyter-rtc/jupyterlab:master`  to this branch for now: https://github.com/jtpio/jupyterlab/tree/rebase-upstream

Just to see the state the tests after picking up changes from upstream.

**Comment by hbcarlos** [comment]
Yes, I added the option `--detectOpenHandles`. We should revert this commit.
https://github.com/jupyter-rtc/jupyterlab/pull/20/commits/2c780db1e8e35def013c878841c45395d97580cc

btw, after rebasing from upstream, service tests work again.

**Comment by jtpio** [comment]
This should now be fixed. See #24 and #25 for more details.
