### ISSUE TITLE
Rebase on upstream JupyterLab

### ISSUE THREAD

**Issue by jtpio** [jupyter-rtc/jupyterlab#24]
An issue to track progress on rebasing onto the upstream JupyterLab.

The idea is to grab the latest changes from core lab to see if they can help fix tests like `js-services`.

cc @dmonad @hbcarlos @echarles

**Comment by jtpio** [comment]
The rebased branch: https://github.com/jupyter-rtc/jupyterlab/tree/rebase-upstream

To see the diff against upstream JupyterLab: https://github.com/jupyterlab/jupyterlab/compare/master...jupyter-rtc:rebase-upstream

To check the `js-services` tests running CI for this branch: https://github.com/jupyter-rtc/jupyterlab/runs/2246363326

(they have been moved to the flaky GitHub Actions workflow)

**Comment by jtpio** [comment]
Also for reference this was the only conflict:

```diff
diff --cc packages/docregistry/package.json
index c39e54771,3b22d95f2..000000000
--- a/packages/docregistry/package.json
+++ b/packages/docregistry/package.json
@@@ -59,7 -59,8 +59,12 @@@
      "@lumino/disposable": "^1.4.3",
      "@lumino/messaging": "^1.4.3",
      "@lumino/signaling": "^1.4.3",
++<<<<<<< HEAD
 +    "@lumino/widgets": "^1.19.0"
++=======
+     "@lumino/widgets": "^1.18.0",
+     "yjs": "^13.5.3"
++>>>>>>> integrate docprovider into docregistry
    },
    "devDependencies": {
      "@jupyterlab/testutils": "^3.1.0-alpha.3",
```

**Comment by dmonad** [comment]
I disabled the python `yjs_echo_ws` server and made the context non-collaborative. Then I rebased everything (I hope this fixes the services tests).

The branch is [`disable_yjs_ws_rebased`](https://github.com/jupyter-rtc/jupyterlab/tree/disable_yjs_ws_rebased)

All tests are running here: https://github.com/jupyter-rtc/jupyterlab/actions

Let's try to get all tests running again, even if it meant to disable features that we implemented in `jupyter-rtc`.

If we can get `services` to run again, I can get the other tests to run by disabling the metadata synchronization.

**Comment by echarles** [comment]
Are we sure we don't fall into some "flaky" tests? Are the failing test in this repo successfull on the jupyterlab master branch?

**Comment by echarles** [comment]
BTW to make it more clear, we could create the `rtc` branch here and make it the default, merging our PR in that `rtc`branch.

**Comment by jtpio** [comment]
>  Are the failing test in this repo successfull on the jupyterlab master branch?

Yes they have been green most of the time in the past days / weeks. `js-apputils` and `js-services` are still part of the flaky group because yes sometimes they fail or timeout (but much less often than before).

**Comment by jtpio** [comment]
> BTW to make it more clear, we could create the `rtc` branch here and make it the default, merging our PR in that `rtc`branch.

Sure. GitHub now handles branch renames in a convenient way normally.

![image](https://user-images.githubusercontent.com/591645/113304855-b6249300-9302-11eb-8444-a97f02aaefd6.png)

**Comment by jtpio** [comment]
This is the diff for the `services` package compared to upstream:

```diff
diff --git a/packages/services/package.json b/packages/services/package.json
index bf9363bc1..ad1dbfe31 100644
--- a/packages/services/package.json
+++ b/packages/services/package.json
@@ -39,7 +39,7 @@
     "clean": "rimraf lib && rimraf tsconfig.tsbuildinfo",
     "docs": "typedoc src",
     "prepublishOnly": "jlpm run build && webpack",
-    "test": "jest",
+    "test": "jest --detectOpenHandles",
     "test:cov": "jest --collect-coverage",
     "test:debug": "node --inspect-brk node_modules/.bin/jest --runInBand",
     "test:debug:watch": "node --inspect-brk node_modules/.bin/jest --runInBand --watch",
```

Should that change be reverted? (mentioned in https://github.com/jupyter-rtc/jupyterlab/issues/23#issuecomment-811913866)

**Comment by echarles** [comment]
FWIW `--detectOpenHandles` has been introduced to https://github.com/jupyter-rtc/jupyterlab/pull/20

**Comment by echarles** [comment]
<img width="494" alt="Screenshot 2021-04-01 at 16 19 35" src="https://user-images.githubusercontent.com/226720/113308056-136e1380-9306-11eb-9523-1fb76343c4a0.png">

```
The default branch has been renamed!
master is now named rtc

If you have a local clone, you can update it by running:

git branch -m master rtc
git fetch origin
git branch -u origin/rtc rtc
git remote set-head origin -a
```

**Comment by hbcarlos** [comment]
> Should that change be reverted? (mentioned in #23 (comment))

Yes, should be reverted. That does nothing.

**Comment by jtpio** [comment]
Just forced the `rebase-upstream` branch pushed to the now rename `rtc` branch:

![image](https://user-images.githubusercontent.com/591645/113311554-b96f4d00-9309-11eb-93db-cf66f242601b.png)

(a PR was merged in JupyterLab in the meantime hence the "2 commits behind") 

https://github.com/jupyterlab/jupyterlab/compare/master...jupyter-rtc:rtc

**Comment by jtpio** [comment]
> Yes, should be reverted. That does nothing.

@hbcarlos do you want to open a PR to revert it?

**Comment by jtpio** [comment]
Thanks all.

Closing as fixed and rebased: https://github.com/jupyter-rtc/jupyterlab
