### ISSUE TITLE
CI is still failing

### ISSUE THREAD

**Issue by dmonad** [jupyter-rtc/jupyterlab#28]
A lot of CI tests are still failing. How can we get them running again?

**Comment by echarles** [comment]
@dmonad @hbcarlos @jtpio 8 hours ago, this has shown 100% green https://github.com/jupyter-rtc/jupyterlab/actions/runs/712837644

**Comment by echarles** [comment]
@dmonad I have just merged https://github.com/jupyter-rtc/jupyterlab/pull/29 based on a green CI. I guess you can close this issue.

**Comment by jtpio** [comment]
Looks like the remaining failing checks are:

- the [release check](https://github.com/jupyter-rtc/jupyterlab/runs/2258369092), which seems to depend on `@jupyterlab/nbmodel` being published to npm. I think this is normal for now and was the case upstream when adding new packages before (although it would be nice to not depend on published packages)
- the [examples check](https://github.com/jupyter-rtc/jupyterlab/runs/2258369208), which seems to be giving the following error (and might be fixable):

```
$ node scripts/ensure-buildutils.js && node buildutils/lib/ensure-repo.js
(node:2201) UnhandledPromiseRejectionWarning: Error: Cannot find module 'buffer/package.json'
```

**Comment by echarles** [comment]
Yeah, just posted the same feedback on https://github.com/jupyter-rtc/jupyterlab/pull/29#issuecomment-812819035 4 minutes ago

I have merged although there are 2 CI failures unrelated :

Linux release check '@jupyterlab/nbmodel@3.1.0-alpha.3' is not in the npm registry. => we can fix that later on, should not block us with the dev as it is about release...

Linux Examples: ERR! Failed at the @jupyterlab/example-federated@2.2.0-alpha.3 build:middle script. => I have that issue on my local env with the jupyterlab master branch, so not linked to rtc branch

**Comment by jtpio** [comment]
> Linux Examples: ERR! Failed at the @jupyterlab/example-federated@2.2.0-alpha.3 build:middle script. => I have that issue on my local env with the jupyterlab master branch, so not linked to rtc branch

Although this one seems to be passing upstream: https://github.com/jupyterlab/jupyterlab/runs/2246740238

**Comment by dmonad** [comment]
Makes sense. So we need to publish these packages to fix the `release_test` CI test. Who could publish these new packages for us? Can we do it now, or must this be done after the merge?

I will open a separate ticket for fixing the `examples` test. If it runs upstream, we should be able to run them too (even if we have to do another rebase).

**Comment by dmonad** [comment]
Closing in favor of #31 and #40
