### ISSUE TITLE
Fix `examples check` CI

### ISSUE THREAD

**Issue by dmonad** [jupyter-rtc/jupyterlab#31]
The  `examples check` CI runs upstream, so we should be able to run them as well somehow.

**Comment by jtpio** [comment]
Will look into this.

It's possible we'll need to apply a similar fix as in https://github.com/jupyter-rtc/jupyterlab/commit/d6a41676bf7cbb41940f7bca28ea9ea3197be1ea for the webpack config of some of the examples (at least for now).

**Comment by jtpio** [comment]
Opened https://github.com/jupyter-rtc/jupyterlab/pull/38 for a potential fix.

**Comment by echarles** [comment]
@jtpio This should be closed I think.

**Comment by jtpio** [comment]
Yes, closing as fixed by the latest rebase.
