### ISSUE TITLE
Cells should allow undoing a change

### ISSUE THREAD

**Issue by echarles** [jupyter-rtc/jupyterlab#52]
We have a regression for the cells test.

```
test/model.spec.ts
  @jupyterlab/notebook
    NotebookModel
      #cells
        ✕ should allow undoing a change

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by jtpio** [comment]
For reference:

![image](https://user-images.githubusercontent.com/591645/114836095-939a7b80-9dd2-11eb-86aa-ff37804a8226.png)

Example run: https://github.com/jupyter-rtc/jupyterlab/pull/51/checks?check_run_id=2350227392

**Comment by jtpio** [comment]
Looking into that a little bit.

It might be related to the cell id not being tracked by the undo manager. The cell id is one the changes brought in the last rebase.

The `nbcell` is created here and passed the cell type: 

https://github.com/jupyter-rtc/jupyterlab/blob/0768a7da171be1bd531f8430087a808ded1409cd/packages/codeeditor/src/editor.ts#L336-L339

While the id of the cell is kept in the cell model here: 

https://github.com/jupyter-rtc/jupyterlab/blob/0768a7da171be1bd531f8430087a808ded1409cd/packages/cells/src/model.ts#L169

And the test expects to find the same cell id after undoing a deletion.

**Comment by dmonad** [comment]
Fixed
