### ISSUE TITLE
Publish nbmodel & docprovider package and re-enable splice tests

### ISSUE THREAD

**Issue by echarles** [jupyter-rtc/jupyterlab#53]
We should revert the disabling of the splice test, probably when the nbformat package will be release, TBC.

The disabling can be seen in this commit.

https://github.com/jupyter-rtc/jupyterlab/commit/1953b84f3b7235820f0765c3caa8b3829a6f645b

**Comment by jtpio** [comment]
Opened https://github.com/jupyterlab/jupyterlab/pull/10230 in the lab repo to fix it.

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/10230
