### ISSUE TITLE
New rebase

### ISSUE THREAD

**Issue by jtpio** [jupyter-rtc/jupyterlab#56]
A new alpha release has been published upstream (`3.1.0-alpha.5`)

So it would be nice to do another rebase to make sure version numbers are aligned with the new `docprovider` and `nbmodel` packages.

cc @dmonad who was interested in doing it

**Comment by dmonad** [comment]
Done, waited for the tests which were working fine. 

FYI @hbcarlos  I force-pushed a rebase to `rtc`
