### ISSUE TITLE
Testing compatibility with extensions

### ISSUE THREAD

**Issue by dmonad** [jupyter-rtc/jupyterlab#60]
In our previous attempt, Fernando found that our RTC solution broke several extensions. We took great effort to keep compatibility in this new attempt. We should test compatibility with plugins before merging with upstream.

**Comment by hbcarlos** [comment]
So far, extensions are working.
I tried:

- [JupyterLab-LSP](https://github.com/krassowski/jupyterlab-lsp)
- [JupyterLab-DrawIO](https://github.com/QuantStack/jupyterlab-drawio)
- [Voila-Gridstack](https://github.com/voila-dashboards/voila-gridstack)

**Comment by dmonad** [comment]
Thanks for trying out some extensions @hbcarlos. It seems that @krassowski also checked out some extensions https://github.com/jupyterlab/jupyterlab/pull/10118#pullrequestreview-654088944

There seems to be only one issue that is tracked in #64
