### ISSUE TITLE
Remove cell

### ISSUE THREAD

**Issue by hbcarlos** [jupyter-rtc/jupyterlab#63]
## Description

After moving cells, when removing a cell the second view removes the wrong one.
Looks like cells get desynchronized because after removing a cell if you play with the remaining ones, they show the wrong behaviour. Cells get duplicated when moving around, every view shows different cells, ...

**Comment by dmonad** [comment]
This issue has been fixed I think. Can you please check again?

**Comment by hbcarlos** [comment]
No, is not. I just installed fresh from the rtc branch and still there.
When removing a cell always removes the first one on the second screen.

**Comment by dmonad** [comment]
Oh no. Now I can see it as well. Gonna fix that next.

**Comment by echarles** [comment]
Yes, I was going to open an issue and now sees this issue already captures it. Posting the screencast as reproducer.

![Untitled](https://user-images.githubusercontent.com/226720/116661351-98475e00-a994-11eb-95b1-1d3c2c9f4548.gif)

**Comment by hbcarlos** [comment]
Solved in #66
