### ISSUE TITLE
Completer moves cursor to the begining of the completed word

### ISSUE THREAD

**Issue by hbcarlos** [jupyter-rtc/jupyterlab#64]
## Description
When using the completer, the cursor moves to the beginning of the word instead of the end.

## Reproduce
Use tab to autocomplete code in a cell.

## Expected behaviour
When completing, the cursor should move to the end of the word.

## Context
N/A

**Comment by krassowski** [comment]
This behaviour is coming from this line:

https://github.com/yjs/y-codemirror/blob/cdf74be34db61f642657fcdf29077f07ca31e156/src/y-codemirror.js#L77

which i believe comes after:

https://github.com/jupyterlab/jupyterlab/pull/10118/files#diff-97da20fee89900086c0fb186cd24ccafbb6f132126dcff536d6e437a66ac8ab5R195-R196

That action `cm.setSelection` call results in moving the cursor to the beginning of the token; not sure it this should happen after each remove/insert action. CC @dmonad  

![narrowing-down](https://user-images.githubusercontent.com/5832902/117185275-94bb3900-add1-11eb-8c91-154e2226640d.gif)

**Comment by hbcarlos** [comment]
Thanks for tracking this issue @krassowski

**Comment by dmonad** [comment]
Fixed in https://github.com/jupyterlab/jupyterlab/pull/10234
