### ISSUE TITLE
How to install this alongside existing JupyterLab installation?

### ISSUE THREAD

**Issue by SaadBazaz** [jupyter-rtc/jupyterlab#70]
Hey there, 
I know this can be either a very motivating or a very depressing message based on how you take it, but... What's the progress on the release? Can I install this alongside my existing JupyterLab installation (macOS Big Sur)? If yes, any guidelines would be appreciated.

P.S: I'm just a normal user who wants to work realtime with a friend.

**Comment by jtpio** [comment]
Thanks @SaadBazaz for the interest!

This repo is a fork of [JupyterLab](https://github.com/jupyterlab/jupyterlab), and there is an open PR to add RTC to JupyterLab by default: https://github.com/jupyterlab/jupyterlab/pull/10118

In the meantime, you might want to try it out locally by cloning https://github.com/jupyter-rtc/jupyterlab and following the dev instructions: https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html

Or using the Binder link from the PR mentioned above, which will spawn a JupyterLab instance with real time collaboration on https://mybinder.org: https://mybinder.org/v2/gh/jupyter-rtc/jupyterlab/rtc?urlpath=lab-dev

**Comment by SaadBazaz** [comment]
Sounds awesome. Will try using this with a friend.
Thanks for the guidance, and good luck my bros
