### ISSUE TITLE
Disable RTC by default and add config to enable it via feature flag.

### ISSUE THREAD

**Issue by dmonad** [jupyter-rtc/jupyterlab#73]
Basically we just have to toggle this boolean to disable collaboration. It is already disabled by default and is explicitly set to true when initializing docregistry/context. https://github.com/jupyterlab/jupyterlab/pull/10118/files#diff-bd91309321cead1ad13aa66f461c81110113c117fababf12ea04e346b0b5afb5R92 

Somebody mentioned that `PageConfig` would be responsible for feature flags.

Please also provide a short description on how to enable the feature flag if users want to opt in.

@jtpio @hbcarlos If you have time and want to start working on this please assign this ticket to yourself. Otherwise, I'll try to do this tonight.

**Comment by jtpio** [comment]
An existing example for this would be the `exposeAppInBrowser` option: 

https://github.com/jupyter-rtc/jupyterlab/blob/dca19636dd643a3ffcb031918000627182b178a3/dev_mode/index.js#L210-L216

This could even be a cli flag, for example called `--collaborative`, similar to:

https://github.com/jupyter-rtc/jupyterlab/blob/dca19636dd643a3ffcb031918000627182b178a3/jupyterlab/labapp.py#L492-L495

In this example, the flag is then passed to the page config here:

https://github.com/jupyter-rtc/jupyterlab/blob/dca19636dd643a3ffcb031918000627182b178a3/jupyterlab/labapp.py#L662

**Comment by hbcarlos** [comment]
Thanks for all the info!

**Comment by jtpio** [comment]
Fixed by #75.
